### ISSUE TITLE
Where to discuss/feedback on the server-side part of Telegram?

### ISSUE THREAD

**Issue by Flohack74** [telegram-mtproto/awesome-telegram#3]
Hello,

this is Florian from UBports (https://ubports.com/) - the successor project of Ubuntu Touch by Canonical. We are very interested to improve/adapt our current unofficial Telegram client. Also we got some remarks/feedback for the server side. But so far we cannot get in touch with you. Would that be possible? I think both sides could benefit from that.

BR Florian

**Comment by sovietspaceship** [comment]
Hi Florian,

If you are interested in improving your client then you are welcome to do so and we have plenty of resources to help you. The only thing I do not understand is how server-side code matters in this regard. If you can be a bit more specific with your questions it would help a lot. Thank you.

**Comment by stek29** [comment]
@Flohack74 try pinging tg on Twitter, asking support
You could probably also try contacting person with number +<the answer to life the universe and everything>

**Comment by Flohack74** [comment]
Hi,

thanks for the answer. My specific problem is that the server API sends me messages that are above the API level our App supports. The problem is we are very far away with catching up with the latest API, and in general the server respects and still supports our old API.

But we found a case now where we receive a message from a higher API level that crashes the App. I can of course start adding exceptions for those messages, but in general it would be a benefit for Telegram if they check their code for "tightness" of all API messages in their level (not leaking them down or even up, could also happen).

It is very hard to find these kind of errors on the client side since they appear very rarely (sometimes have to wait days until it happens) and I think this would also be much easier to fix it on the server, and all clients can benefit from it.

BR

**Comment by sovietspaceship** [comment]
Hi Florian,

maintaining the API manually is hard and error-prone. Clients are expected to compile their API definitions from the schema (of which you can find updated versions [here](https://github.com/stek29/tl-schema)).
Upgrading to a new schema is generally painless and only involves updating a schema file and rebuilding the project. If you client is not structured like this I strongly suggest you consider this approach.
As I said, there are plenty of resources for help, like this list which other developers and I compiled for this very purpose. Also, if the client you are working on is open source, I would be glad to add it to the list.

Regards

**Comment by stek29** [comment]
I'm pretty sure they'd ignore you, since they don't like third-party clients so much, and their apps are always updated/are error prone so they won't really care.

You can still try contacting the guy I mentioned.

**Comment by Flohack74** [comment]
@sovietspaceship I am maintaining the unofficial Telegram client for the Ubuntu Touch mobile OS (now run by UBports) - see https://github.com/ubports/telegram-app.

Upgrading to a new schema cannot be painless as they add new data fields to the constructors, your application needs to fetch them in the right order, and probably also do smth with this new information, or add new data to messages being sent. The schema changes for a reason, not just to increase the numbers :). We use an API generator made by the Cutegram guys, itś indeed very helpful.

But to give one example, adding captions to media messages involves being able to send & receive them. Until I have this functions also added to the GUI I cannot upgrade to the API level where these captions have been introduced. At the current pace of Telegram firing out new features every other week (think about VoIP now) it would be very important to support also older clients. In fact we are happy that an API is still supported which is over 1 year old. But we would be more than happy if e.g. the official docu pages would be updated more often. Currently they are stuck at layer 23 or so, also secret chats is not up2date: https://core.telegram.org/schema/end-to-end

BR Florian

**Comment by stek29** [comment]
Speaking of secret chats, I have newer schema for schats, I'll upload it to tl-schema repo with layer 70 when I get home.

Docs... Well, they always say they don't have enough resources for that, and I tend to agree. 
They might have some internal docs, but I'm pretty sure they don't since sometimes when you ask devs they say "I can't remember that" and if there were good docs they'd probably just copy the answer from there. 
And they don't have any list of errors, even internal one. At least they didn't some time ago, or devs lied to me. 

> But to give one example, adding captions to media messages involves being able to send & receive them. Until I have this functions also added to the GUI I cannot upgrade to the API level where these captions have been introduced.  

Just ignore those captions, since they don't break anything.

> Upgrading to a new schema cannot be painless as they add new data fields to the constructors, your application needs to fetch them in the right order, and probably also do smth with this new information, or add new data to messages being sent. 

It shouldn't be hard to update it. If you don't have easy way to do that, you're probably writing your app in wrong way, and it would be even more painful in future.

And once again, people who are on this report are mostly tg enthusiasts, the only way to contact someone who can solve this is to use ways I posted in previous comments. You may also try to write them an email, for example to security one. But I'm sure they won't spend time on this, since as I said already they don't really like third party clients much.

**Comment by Flohack74** [comment]
@stek29 thx for your thoughts...

I can just say that if you are going to build smth in a sustainable way then documents must come before coding. Enough said :)

I can ignore captions, but if they change lets say the PeerID from an int to a list of ints, I can´t. Why this change was necessary? What is the meaning of having multiple peers? How to upgrade the local SqLite Db etc. etc. All these things will come with the API changes. The caption is optional, but a lot of things aren´t.

Our secret chats are broken on the devices because we ignore the PFS which was introduced on a later API level. PFS is documented very well and I am sure I can implement this. But in lot of other cases one can only guess.

E.g. this change, how you think you will ignore its consequences and still have a working client:
```
// documentAttributeSticker#994c9882 alt:string = DocumentAttribute;
// messages.allStickers#dcef3102 hash:string packs:Vector<StickerPack> documents:Vector<Document> = messages.AllStickers;
documentAttributeSticker#3a556302 alt:string stickerset:InputStickerSet = DocumentAttribute;
messages.allStickers#5ce352ec hash:string packs:Vector<StickerPack> sets:Vector<StickerSet> documents:Vector<Document> = messages.AllStickers;
```

If they do not like 3rd party clients, why call it "open source" then? In such a thinking it sounds to me that this is only a marketing argument, or a classical abuse of the matter. True open source means also to embrace the participation of others, to gain new ideas. And be open for input, discussion and bug reports.

BR

**Comment by sovietspaceship** [comment]
Hi Florian,

of course you have to change the program to support the changes in the API. What I described is just the process of updating the API layer, which should be automatic so you can focus on implementing features instead of dealing with the protocol schema.

The fact that 3rd party clients are always not well received is that in some cases there was an abuse of the platform and of license terms. Other than that, any project is welcome and, in fact, third-party apps heavily influenced the design of the official clients and features, from theme support to bots. In some cases Telegram itself provides funding and prizes to these efforts. Regarding open source, Telegram is open for input and bug reports, as you can see [here](https://github.com/telegramdesktop/tdesktop/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20is%3Amerged). Open source is different from open API, and the current status of the API is unclear. Protocol schemas are still being published, just not on the official website.

The only issue currently is that the docs are outdated, and everyone is well aware of that.

**Comment by stek29** [comment]
Third party apps aren't welcomed, and that's a citate.
I think it's because of reasons @sovietspaceship posted, and also because "we're open source" marketing strategy isn't needed anymore. They have their official apps for all major platforms (made by guys mostly from VK who won competition) and also that strategy isn't that good.

Afaik transitex doesn't consider telegram opensource anymore, and others shouldn't too, no matter what's said on their site.

Protocol schemes are being published just because they're used by tdesktop and webogram, and that's not publishing, that's digging the sources.
